services:
  fks_nodes:
    build:
      context: .
      dockerfile: shared/shared_docker/templates/rust.Dockerfile
    working_dir: /app
    environment:
      TZ: America/Toronto
      SERVICE_PORT: 5000
      RUST_LOG: info
    ports:
      - "5000:5000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/app/logs
      - rust_target:/app/target
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  rust_target:

networks:
  fks_net:
    name: fks_net