services:
  fks_node_network:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s

networks:
  fks_net:
    name: fks_net