name: fks_nodes CI

concurrency:
  group: fks_nodes-ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Dockerfile*'
      - '.github/workflows/fks_nodes-ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Dockerfile*'
      - '.github/workflows/fks_nodes-ci.yml'
  workflow_dispatch: {}

jobs:
  test:
    name: Unit Tests (Rust)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: fks_nodes-rust-cache

      - name: Check code format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build release
        run: cargo build --release

  docker-build:
    name: Docker Build & Smoke
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    env:
      SERVICE_SLUG: node_network
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: local/fks
          tags: |
            type=ref,event=branch,prefix=nodes-
            type=sha,prefix=nodes-
            type=raw,value=nodes-latest

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
            context: .
            file: Dockerfile.simple
            push: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              SERVICE_RUNTIME=rust
              SERVICE_TYPE=node_network
              BUILD_TYPE=cpu

      - name: Smoke test
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker run --rm --name fks_nodes_test "$TAG" --help || echo 'Basic smoke test completed'

      - name: Export image artifact
        run: |
          docker save $(echo "${{ steps.meta.outputs.tags }}" | head -n1) | gzip > fks_nodes-image.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: fks_nodes-image
          path: fks_nodes-image.tar.gz
